---
-   id: license-check-pipenv
    name: Check the licenses pipenv environment
    description: This hook scans the local Pipfile against a configured list of allowed open source licenses.
    entry: python -m license_checks.pipenv
    files: Pipfile
    language: python
-   id: license-check-npm
    name: Check the licenses npm environment.
    description: This hook scans the package. a configured list of allowed open source licenses.
    entry: python -m license_checks.npm
    files: package.json
    language: python
