---
- id: license-check-gradle
  name: Check the licenses of the gradle environment.
  description: This hook scans the the gradle dependency list againt a configured list of allowed open source licenses.
  entry: license-check-gradle
  files: build.gradle
  language: python
- id: license-check-maven
  name: Check the licenses of the maven environment.
  description: This hook scans the the maven dependency list againt a configured list of allowed open source licenses.
  entry: license-check-maven
  files: pom.xml
  language: python
- id: license-check-npm
  name: Check the licenses of the npm environment.
  description: This hook scans the package. a configured list of allowed open source licenses.
  entry: license-check-npm
  files: package.json
  language: python
- id: license-check-pipenv
  name: Check the licenses of the pipenv environment
  description: This hook scans the local Pipfile against a configured list of allowed open source licenses.
  entry: license-check-pipenv
  files: Pipfile
  language: python
