name: test and build
on:
  pull_request:
    branches: [ main, v3 ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: run tests
        run: make test
      - name: build binary
        run: make binary
